name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./
          server-dir: /home/indt5495/public_html/digitalkreasigroup.com/indofazz/
          state-name: ftp-state.txt
          dry-run: false
          dangerous-clean-slate: false
          exclude: |
            - .DS_Store
            - .git
            - .github
            - LICENSE
            - README.md
          log-level: standard
          security: strict
