name: Pull from FTP

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pull script
        run: python ./digitalkreasi/dev-app/.github/workflows/pull.py
